### ISSUE TITLE
Invite to group channel

### ISSUE THREAD

**Issue by IordacheClaudiu** [ChatCamp/ChatCamp-iOS-SDK#1]
Hi guys,
It might not be right place to raise this issue but I have a question about `https://api.chatcamp.io//api/1.0/group_channels.invite` endpoint. 
<img width="1663" alt="screenshot 2019-01-09 at 17 37 42" src="https://user-images.githubusercontent.com/4499126/50909833-4f6ee280-1435-11e9-9a3e-5228b719ebc0.png">

It seems the status for invited user is marked as `accepted` instead of `invited`. Is this the desired behaviour?

Thanks.

**Comment by darklrd** [comment]
There is a setting called `Group Channel Auto Accept` in [ChatCamp Dashboard](https://dashboard.chatcamp.io) which if set to `true` would result in this behaviour. 

![image](https://user-images.githubusercontent.com/342563/50940810-67337e80-14a8-11e9-845c-e4883f0d3359.png)
